AWSTemplateFormatVersion: 2010-09-09
Resources:
  ServiceQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 30
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          'Fn::GetAtt': DeadLetterQueue.Arn
        maxReceiveCount: 10
  DeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      FifoQueue: true
  DeadLetterResponseQueue:
    Type: 'AWS::SQS::Queue'
Outputs:
  ServiceQueueArn:
    Value:
      Fn::GetAtt:
        - ServiceQueue
        - Arn
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-ServiceQueueArn'
  ServiceQueue:
    Value:
      Ref: ServiceQueue
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-ServiceQueue'